namespace ResearchCruiseApp.Infrastructure.Persistence.Initialization.InitialData;

internal class InitialUgUnitData
{
    public static string[] UgUnitsNames =>
        new[]
        {
            "Administracja Rektora i Jednostki Ogólnouniwersyteckie",
            "Rektor (0000)",
            "Uniwersyteckie Centrum Mediacji i Arbitrażu (0P00)",
            "Sekretariat Rektora (0100)",
            "Centrum Filmowe im. Andrzeja Wajdy (0N00)",
            "Biuro Prawne (0300)",
            "Biuro Organizacji (0400)",
            "Biuro Audytu Wewnętrznego (0500)",
            "Biuro Kontroli Wewnętrznej (0600)",
            "Szkoły Doktorskie (0C00)",
            "Szkoła Doktorska Teorii Informacji Kwantowej (0C50)",
            "Biuro Bezpieczeństwa i Oceny Ryzyka (0700)",
            "Biuro Rzecznika ds. Równego Traktowania i Przeciwdziałania Mobbingowi (800)",
            "Centrum Produkcji Filmowej i Dokumentalnej (0E00)",
            "Uniwersytecki Ośrodek Badań Stosowanych i Międzyobszarowych (0M00)",
            "Centrum Terapii Fagowych (0M50)",
            "Centrum Badań Memlingowskich (0M20)",
            "Centrum Studiów Azji Wschodniej (OM40)",
            "Międzynarodowe Centrum Studiów nad Granicami (0M10)",
            "Międzynarodowe Centrum Badań nad Szczepionkami Przeciwnowotworowymi (International Centre for Cancer Vaccine Science) (0B00)",
            "Międzynarodowe Centrum Teorii Technologii Kwantowych (International Centre for Theory of Quantum Technologies) (0A00)",
            "Biuro Wsparcia Badan i Współpracy z Przemysłem",
            "Sekcja ds. Badań i Rozwoju.",
            "Sekcja Administracyjnego Wsparcia Badań",
            "Zespół Wielofotonowej Optyki Kwantowej i Kwantowej Informacji",
            "Zespół Fundamentalnych Podstaw Technologii Kwantowych",
            "Zespół Nowych Zasobów Kwantowych",
            "Zespół Nowych Zasobów Kwantowych i Termodynamiki Kwantowej",
            "Zespół Układów Otwartych związanych z Optyką Kwantową",
            "Zespół Kwantowego Cyberbezpieczeństwa i Komunikacji",
            "Archiwum UG (0H00)",
            "\"Gazeta Uniwersytecka\" Pismo Społeczności Akademickiej UG (0F00)",
            "Prorektor ds. Współpracy Międzynarodowej (4000)",
            "Sekretariat Prorektora ds. Współpracy Międzynarodowej (4100)",
            "Biuro Współpracy Międzynarodowej (4200)",
            "Sekcja Obsługi Profesorów Zagranicznych (4230)",
            "Sekcja Obsługi Studentów Zagranicznych (4210)",
            "Sekcja Obsługi Programu Erasmus+ (4220)",
            "Biuro Projektu European University of the Seas – SEA-EU (4300)",
            "Centrum J.G. Herdera (4B00)",
            "Instytut Konfucjusza Uniwersytetu Gdańskiego (4A00)",
            "Akademickie Centrum Języka Polskiego i Kultury Polskiej dla Cudzoziemców (4D00)",
            "Prorektor ds. Studentów i Jakości Kształcenia (3000)",
            "Biuro Karier (3700)",
            "Biuro Kształcenia (3200)",
            "Biuro Rekrutacji (3400)",
            "Biuro Stypendialne (3500)",
            "Biuro ds. Osób z Niepełnosprawnością (3600)",
            "Centrum Wychowania Fizycznego i Sportu (3D00)",
            "Biuro Centrum (3D10)",
            "Centrum Kursów i Szkoleń (3800)",
            "Biuro ds. Indywidualnych Studiów Międzydziedzinowych (3900)",
            "Centrum Języków Obcych (3C00)",
            "Sekcja ds. Hospitacji (3C70)",
            "Zespół Lektorów Języka Angielskiego (3C20)",
            "Zespół Lektorów Języków Germańskich, Romańskich i Słowiańskich (3C30)",
            "Język łaciński",
            "Język włoski",
            "Język rosyjski",
            "Język szwedzki",
            "Język polski (dla obcokrajowców)",
            "Język niemiecki",
            "Język francuski",
            "Język hiszpański",
            "Sekcja ds. Metodyki i Jakości Kształcenia (3C50)",
            "Sekcja ds. Tłumaczeń (3C60)",
            "Centrum Kształcenia Nauczycieli (3I00)",
            "Akademickie Centrum Kultury UG \"Alternator\" (3A00)",
            "Gdański Uniwersytet Trzeciego Wieku (3B00)",
            "Biuro GUTW (3B10)",
            "Centrum Aktywności Studenckiej i Doktoranckiej (3F00)",
            "Biuro Centrum Aktywności Studenckiej i Doktoranckiej (3F50)",
            "Biuro Parlamentu Studentów UG (3F10)",
            "Biuro Rady Doktorantów (3F20)",
            "Czasopismo \"Progress\" (3F40)",
            "Centrum Doskonalenia Dydaktycznego i Tutoringu (3E00)",
            "Biuro Jakości Kształcenia (3E10)",
            "Prorektor ds. Badań Naukowych (1000)",
            "Biuro Nauki (1200)",
            "Biuro Rzecznika Rzetelności Naukowej (1300)",
            "Biuro Wsparcia Realizacji Projektów (1700)",
            "Samodzielne Stanowisko Koordynatora systemu POL-on (1600)",
            "Wydawnictwo UG (1B00)",
            "Zakład Poligrafii (1B10)",
            "Księgarnia Uniwersytecka (1B20)",
            "Biblioteka UG (1A00)",
            "Sekcja Zarządzania Danymi Badawczymi i Otwartej Nauki (1AP0)",
            "Samodzielna Sekcja ds. Technik Multimedialnych Obiektu Biblioteka Główna",
            "Oddział Informatyzacji",
            "Oddział Digitalizacji Zbiorów",
            "Oddział Gromadzenia i Uzupełniania Zbiorów",
            "Oddział Opracowania Zbiorów",
            "Oddział Bibliografii i Bibliometrii",
            "Oddział Zbiorów Specjalnych",
            "Oddział Udostępniania i Informacji (1AM0)",
            "Czytelnia III - Nauki ścisłe",
            "Wypożyczalnia",
            "Czytelnia III - Nauki Społeczne",
            "Czytelnia II - Nauki humanistyczne",
            "Czytelnia I - Kultura i Sztuka",
            "Czytelnia II - Nauka o literaturze, Językoznawstwo",
            "Sekcja Zasobów Bibliotecznych (1AN0)",
            "Sekcja Usług Introligatorskich (1AR0)",
            "Biblioteka Neofilologiczna Uniwersytetu Gdańskiego",
            "Biblioteka Ekonomiczna Uniwersytetu Gdańskiego",
            "Biblioteka Humanistyczna Uniwersytetu Gdańskiego",
            "Biblioteka Prawna Uniwersytetu Gdańskiego",
            "Biblioteka Historii Kultury",
            "Klub Profesora Emerytowanego Uniwersytetu Gdańskiego",
            "Centrum Popularyzacji Nauki (1D00)",
            "Prorektor ds. Współpracy i Rozwoju (9000)",
            "Centrum Badań nad Gospodarką Morską (9D00)",
            "Biuro Współpracy i Rozwoju (9200)",
            "Biuro Wsparcia Przygotowania Projektów – Inkubator Projektowy (9500)",
            "Centrum Transferu Technologii (9A00)",
            "Biuro Analiz i Ekspertyz (9400)",
            "Uniwersyteckie Laboratorium Usług Badawczych (9E00)",
            "Centrum Zrównoważonego Rozwoju (9B00)",
            "Akademickie Centrum Wsparcia Psychologicznego (9C00)",
            "Kanclerz (5000)",
            "Biuro Kanclerza (5900)",
            "Centrum Zamówień Publicznych (5B00)",
            "Dział Monitoringu Realizacji Zamówień Publicznych (5B30)",
            "Dział Zamówień Publicznych (5B10)",
            "Dział Analiz i Wsparcia w Procesach Zakupowych (5B20)",
            "Biuro Armatora z jednostką r/v Oceanograf. (5A00)",
            "jednostka r/v Oceanograf",
            "Sekcja ds. Ubezpieczeń (5600)",
            "Sekcja ds. Rozliczeń (5500)",
            "Ośrodek Konferencyjno-Szkoleniowy UG w Leźnie",
            "Kancelaria Ogólna (5400)",
            "Zastępca Kanclerza ds. Infrastruktury i Administracji (700A)",
            "Centrum Eksploatacji Nieruchomości (7900)",
            "Sekcja Ochrony Mienia (7970)",
            "Dział Administrowania Nieruchomościami (7920)",
            "Biuro Centrum (7910)",
            "Dział Hoteli Asystenckich (7960)",
            "Dział Obiektów Dydaktycznych (7950)",
            "Dział Technicznego Utrzymania Nieruchomości (7930)",
            "Dział Domów Studenckich (7940)",
            "Dział Inwestycji i Remontów (7700)",
            "Straż Uniwersytecka (7200)",
            "Muzeum Uniwersytetu Gdańskiego (7500)",
            "Samodzielne Stanowisko ds. Infrastruktury (7A00)",
            "Samodzielne Stanowisko ds. Przedsięwzięć Innowacyjnych. (7B00)",
            "Samodzielne Stanowisko Koordynatora ds. Budowy Centrum Sportowego (7C00)",
            "Zastępca Kanclerza ds . HR (Q000)",
            "Dział Kadr (Q100)",
            "Dział Płac (Q200)",
            "Sekcja Umów Cywilnoprawnych (0221)",
            "Sekcja Spraw Socjalnych (Q400)",
            "Biuro Bezpieczeństwa Pracy i Ochrony Zdrowia (Q300)",
            "Zastępca Kanclerza ds. Projektów Strategicznych (V000)",
            "Biuro Monitoringu Projektów (V200)",
            "Biuro Projektów Strategicznych i Inicjatyw Rektora (V100)",
            "Zastępca Kanclerza ds. Informatyzacji, Komunikacji i Promocji (8000)",
            "Centrum Informatyczne (8100)",
            "Sekretariat Centrum Informatycznego (81H0)",
            "Sekcja Administratorów Lokalnych (81I0)",
            "Sekcja Systemów Wspomagających Zarządzanie Uczelnią (81L0)",
            "Sekcja Wsparcia Użytkowników - Help Desk (81J0)",
            "Sekcja Zarządzania Infrastrukturą Centralną (81C0)",
            "Sekcja Rozwoju Oprogramowania (81D0)",
            "Sekcja WWW (81E0)",
            "Samodzielne Stanowisko ds. Bezpieczeństwa i Zarządzania Zgodnością IT (81K0)",
            "Centrum Kompetencyjne EZD (8200)",
            "Centrum Komunikacji i Promocji (8300)",
            "Zespół Prasowy (8310)",
            "Zespół Promocji i Kontaktów ze Sponsorami (8340)",
            "Radio MORS (8500)",
            "Kwestor - Główny Księgowy (6000)",
            "Dział Kontrolingu (6010)",
            "Stanowisko Głównego Specjalisty ds. Finansowo-Księgowych (6100)",
            "Sekcja ds. Weryfikacji i Akceptacji Dokumentów (6200)",
            "Zastępca Kwestora ds. Finansów (6500)",
            "Dział Finansowy (6510)",
            "Sekcja Obsługi Kasowej (6511)",
            "Sekcja Sprawozdawczości Statystycznej i Budżetowej (6520)",
            "Sekcja Windykacji (6530)",
            "Zastępca Kwestora ds. Rachunkowości (6400)",
            "Dział Rachunkowości Finansowej (6410)",
            "Sekcja Obsługi Uniwersyteckich Jednostek Oświatowych (6414)",
            "Sekcja Rozliczeń Działalności Dydaktycznej i Funduszy (6415)",
            "Sekcja Rozliczeń Publiczno-Prawnych (6413)",
            "Sekcja ds. Ewidencji Księgowej Projektów (6411)",
            "Sekcja Rozrachunków (6412)",
            "Dział Gospodarowania Rzeczowymi Składnikami Majątku (6420)",
            "Zastępca Kwestora ds. Projektów (6600)",
            "Dział Obsługi Finansowej Projektów (6610)",
            "Wydział Biologii (D000)",
            "Dziekan Wydziału Biologii",
            "Katedra Biologii Eksperymentalnej i Biotechnologii Roślin (D230)",
            "Pracownia Biotechnologii Roślin (D232)",
            "Pracownia Cytologii i Embriologii Roślin (D231)",
            "Pracownia Fizjologii Roślin i Toksykologii (D233)",
            "Prodziekan ds. Nauki",
            "Prodziekan ds. Studenckich i Rozwoju",
            "Prodziekan ds. Kształcenia",
            "Dziekanat Wydziału Biologii (D001)",
            "Katedra Biochemii Ogólnej i Medycznej (D010)",
            "Pracownia Biochemii Białek i Kwasów Nukleinowych (D011)",
            "Pracownia Biochemii Mikroorganizmów (D012)",
            "Katedra Biologii i Genetyki Medycznej (D130)",
            "Pracownia Molekularnych i Komórkowych Podstaw Strategii Nutraceutycznych (D133)",
            "Pracownia Genomiki i Genetyki Człowieka (D132)",
            "Pracownia Sygnalizacji Wewnątrzkomórkowej (D131)",
            "Katedra Genetyki Molekularnej Bakterii (D140)",
            "Laboratorium Izotopowe (D141)",
            "Katedra Biologii Molekularnej (D020)",
            "Katedra Ekologii Roślin (D040)",
            "Pracownia Ekologii Wód Słodkich (D041)",
            "Pracownia Paleoekologii i Archeobotaniki (D042)",
            "Katedra Ekologii i Zoologii Kręgowców (D050)",
            "Pracownia Ekologii i Etologii Kręgowców (D051)",
            "Pracownia Ornitologii (D053)",
            "Katedra Fizjologii Zwierząt i Człowieka (D080)",
            "Pracownia Bioenergetyki (D087)",
            "Pracownia Zwierząt Doświadczalnych (D084)",
            "Pracownia Neurofizjologii i Neurochemii (D085)",
            "Pracownia Neurobiologii (D081)",
            "Pracownia Fizjologii Behawioru i Stresu (D083)",
            "Katedra Genetyki Ewolucyjnej i Biosystematyki (D200)",
            "Pracownia Genetyki (D203)",
            "Pracownia Biosystematyki i Ekologii Bezkręgowców Wodnych (D202)",
            "Pracownia Ewolucji Molekularnej i Bioinformatyki (D201)",
            "Katedra Mikrobiologii (D100)",
            "Pracownia Biologii Ekstremofili (D101)",
            "Katedra Taksonomii Roślin i Ochrony Przyrody (D110)",
            "Pracownia Symbioz Roślinnych (D114)",
            "Pracownia Geobotaniki i Ochrony Przyrody (D111)",
            "Pracownia Lichenologii i Mykologii Eksperymentalnej (D112)",
            "Pracownia Taksonomii Roślin (D113)",
            "Katedra Zoologii Bezkręgowców i Parazytologii (D120)",
            "Pracownia Parazytologii i Zoologii Ogólnej (D121)",
            "Pracownia Zoologii Systematycznej (D122)",
            "Pracownia Entomologii Ewolucyjnej i Muzeum Inkluzji w Bursztynie (D133)",
            "Stacja Badania Wędrówek Ptaków (D150)",
            "Laboratorium Bioobrazowania (D220)",
            "Kolekcja Plazmidów i Drobnoustrojów (D190)",
            "Gdańskie Centrum Zasobów Biologicznych (D210)",
            "Wydział Chemii (T000)",
            "Dziekan Wydziału Chemii",
            "Biuro Dziekana (T002)",
            "Prodziekan ds. Studenckich i Kształcenia",
            "Prodziekan ds. Nauki",
            "Prodziekan ds. Umiędzynarodowienia i Rozwoju",
            "Dziekanat (T001)",
            "Katedra Analizy Środowiska (T010)",
            "Pracownia Analityki i Diagnostyki Chemicznej",
            "Pracownia Analityki i Monitoringu Środowiska",
            "Pracownia Analizy Związków Naturalnych",
            "Pracownia Chemicznych Zagrożeń Środowiska",
            "Katedra Technologii Środowiska (T020)",
            "Pracownia Analityki i Nanodiagnostyki Biochemicznej",
            "Pracownia Materiałów i Procesów Katalitycznych (T023)",
            "Pracownia Fotokatalizy",
            "Pracownia Materiałów i Procesów Katalitycznych",
            "Katedra Chemii i Radiochemii Środowiska (T030)",
            "Pracownia Analityki i Radiochemii Środowiska",
            "Pracownia Chemoinformatyki Środowiska",
            "Pracownia Toksykologii i Ochrony Radiologicznej",
            "Katedra Biotechnologii Molekularnej (T040)",
            "Pracownia Chemii Makromolekuł Biologicznych",
            "Pracownia Bionanotechnologii (T043)",
            "Katedra Chemii Analitycznej (T050)",
            "Pracownia Chemii i Analityki Kosmetyków",
            "Pracownia Chemii Supramolekularnej",
            "Katedra Biochemii Molekularnej (T060)",
            "Pracownia Chemii Bioorganicznej",
            "Pracownia Chemii Związków Biologicznie Czynnych",
            "Katedra Chemii Biomedycznej (T070)",
            "Pracownia Biochemii Strukturalnej",
            "Pracownia Chemii Medycznej",
            "Katedra Chemii Fizycznej (T080)",
            "Pracownia Badań Luminescencyjnych",
            "Pracownia Krystalochemii",
            "Pracownia Sensybilizatorów Biologicznych",
            "Katedra Chemii Ogólnej i Nieorganicznej (T090)",
            "Pracownia Biologicznej Chemii Nieorganicznej",
            "Pracownia Fizykochemii Związków Kompleksowych",
            "Katedra Chemii Bionieorganicznej (T120)",
            "Pracownia Oddziaływań Międzycząsteczkowych",
            "Katedra Chemii Organicznej (T100)",
            "Pracownia Glikochemii",
            "Pracownia Chemii Cukrów",
            "Pracownia Chemii Peptydów",
            "Pracownia Badań Strukturalnych Biopolimerów",
            "Katedra Chemii Teoretycznej (T110)",
            "Pracownia Chemii Kwantowej",
            "Pracownia Modelowania Molekularnego",
            "Pracownia Symulacji Polimerów",
            "Zakład Dydaktyki i Popularyzacji Nauki (T130)",
            "Dział Zaopatrzenia i Obsługi Technicznej (T140)",
            "Sekcja Aparatury i Zamówień Publicznych (T141)",
            "Sekcja Obsługi Technicznej i Magazynowej (T142)",
            "Sekcja Pomiarów Fizyko-Chemicznych (T003)",
            "Wydział Ekonomiczny (E000)",
            "Dziekan Wydziału Ekonomicznego",
            "Sekcja Informatyczna Wydziału Ekonomicznego (E003)",
            "Prodziekan ds. Studenckich i Kształcenia",
            "Prodziekan ds. Nauki i Umiędzynarodowienia",
            "Prodziekan ds. Rozwoju i Współpracy z Otoczeniem Społeczno-Gospodarczym",
            "Biuro Dziekana (E002)",
            "Dziekanat Wydziału Ekonomicznego (E001)",
            "Katedra Biznesu Międzynarodowego (E010)",
            "Zakład Handlu Zagranicznego (E011)",
            "Zakład Strategii Marketingowych (E012)",
            "Zakład Międzynarodowych Stosunków Ekonomicznych (E013)",
            "Zakład Międzynarodowych Rynków Finansowych (E014)",
            "Katedra Transportu i Handlu Morskiego (E030)",
            "Zakład Gospodarki Morskiej (E031)",
            "Zakład Gospodarki Globalnej (E032)",
            "Zakład Gospodarki Elektronicznej (E033)",
            "Katedra Zrównoważonych Procesów Rynkowych (E020)",
            "Katedra Ekonomiki Transportu (E040)",
            "Katedra Ekonomiki i Funkcjonowania Przedsiębiorstw Transportowych (E050)",
            "Katedra Ekonomii Międzynarodowej i Rozwoju Gospodarczego (E060)",
            "Katedra Logistyki (E070)",
            "Katedra Makroekonomii (E080)",
            "Katedra Mikroekonomii (E090)",
            "Katedra Polityki Gospodarczej (E100)",
            "Katedra Polityki Transportowej i Integracji Gospodarczej (E140)",
            "Katedra Rynku Transportowego (E120)",
            "Centrum Badań nad Odpowiedzialnością Korporacyjną (E150)",
            "Międzywydziałowe Studia Podyplomowe MBA, Master of business administration (Wydziały Ekonomiczny i Zarządzania)",
            "Wydział Filologiczny (I000)",
            "Dziekan Wydziału Filologicznego",
            "Biuro Dziekana (I004)",
            "Prodziekan ds. Kształcenia i Współpracy z Otoczeniem",
            "Prodziekan ds. Nauki i Współpracy Międzynarodowej",
            "Prodziekan ds. Studenckich",
            "Dziekanat Wydziału Filologicznego (I001)",
            "Samodzielne Stanowisko Pracy ds. Promocji (I002)",
            "Zespół ds. Aparatury Wydziału (I003)",
            "Instytut Anglistyki i Amerykanistyki (I010)",
            "Zakład Badań nad Literaturą Anglojęzyczną (I011)",
            "Zakład Amerykanistyki (I016)",
            "Zakład Badań nad Sztukami Scenicznymi (I015)",
            "Zakład Glottodydaktyki i Przetwarzania Języka Naturalnego (I014)",
            "Zakład Języka Angielskiego i Językoznawstwa Teoretycznego (I013)",
            "Zakład Translatoryki Anglistycznej (I012)",
            "Instytut Badań nad Kulturą (I090)",
            "Zakład Filmu i Mediów (I091)",
            "Zakład Kulturoznawstwa (I092)",
            "Instytut Filologii Germańskiej (I020)",
            "Zakład Języka Niemieckiego i Translatoryki (I021)",
            "Zakład Literatury i Kultury Niemieckiej (I022)",
            "Instytut Filologii Polskiej (I030)",
            "Zakład Dramatu, Teatru i Widowisk (I035)",
            "Zakład Historii Literatury Polskiej (I033)",
            "Zakład Języka Polskiego (I031)",
            "Zakład Polonistyki Stosowanej (I032)",
            "Zakład Teorii Literatury i Krytyki Artystycznej (I034)",
            "Instytut Filologii Romańskiej (I050)",
            "Zakład Językoznawstwa Romańskiego (I052)",
            "Zakład Iberystyki (I053)",
            "Zakład Literatur Romańskich (I051)",
            "Instytut Lingwistyki Stosowanej (I070)",
            "Instytut Logopedii (I100)",
            "Instytut Rusycystyki i Studiów Wschodnich (I040)",
            "Zakład Języka Rosyjskiego i Przekładoznawstwa (I043)",
            "Zakład Kultury i Języków Azji Wschodniej (I044)",
            "Zakład Pragmatyki Komunikacji i Dydaktyki Języka Rosyjskiego (I041)",
            "Zakład Rosjoznawstwa, Literatury i Kultury Rosyjskiej (I042)",
            "Instytut Skandynawistyki i Fennistyki (I080)",
            "Instytut Studiów Klasycznych i Slawistyki (I060)",
            "Zakład Filologii Klasycznej (I062)",
            "Zakład Slawistyki i Studiów Bałkańskich (I061)",
            "Ośrodek Egzaminacyjny Wydziału Filologicznego (I110)",
            "Telefoniczna Poradnia Językowa Uniwersytetu Gdańskiego",
            "Centrum Teatralne (I110)",
            "Wydział Historyczny (U000)",
            "Dziekan Wydziału Historycznego",
            "Biuro Dziekana (U0002)",
            "Prodziekan ds. Jakości Kształcenia",
            "Prodziekan ds. Badań Naukowych i Współpracy Międzynarodowej",
            "Prodziekan ds. Studentów i Współpracy z Otoczeniem Społeczno-Gospodarczym",
            "Dziekanat Wydziału Historycznego (U001)",
            "Instytut Historii (U100)",
            "Zakład Historii Europy Wschodniej (U113)",
            "Zakład Historii Gdańska, Pomorza i Regionu Nadbałtyckiego (U114)",
            "Zakład Historii Starożytnej (U101)",
            "Zakład Historii Powszechnej Średniowiecza (U102)",
            "Zakład Historii Średniowiecza Polski i Nauk Pomocniczych Historii (U103)",
            "Zakład Historii Nowożytnej (U104)",
            "Zakład Historii XIX wieku (U111)",
            "Zakład Historii XX wieku (U112)",
            "Zakład Historii Myśli i Kultury Politycznej (U108)",
            "Zakład Metodologii Historii, Historii Historiografii i Archiwistyki (U109)",
            "Zakład Edukacji Historycznej (U115)",
            "Instytut Archeologii (U400)",
            "Zakład Archeologii Pradziejowej (U201)",
            "Zakład Archeologii Śródziemnomorskiej (U202)",
            "Zakład Archeologii Średniowiecza i Nowożytności (U203)",
            "Instytut Historii Sztuki (U300)",
            "Zakład Teorii Sztuki (U301)",
            "Zakład Historii Sztuki Średniowiecznej (U302)",
            "Zakład Historii Sztuki Nowoczesnej (U303)",
            "Zakładu Historii Sztuki Nowożytnej (U304)",
            "Instytut Antropologii (U500)",
            "Zakład Etnologii Polski i Antropologii Historii (U502)",
            "Zakład Studiów nad Religią (U503)",
            "Zakład Antropologii Nowego Świata i Studiów Etnicznych (U501)",
            "Wydział Matematyki, Fizyki i Informatyki (K000)",
            "Dziekan Wydziału Matematyki, Fizyki i Informatyki",
            "Prodziekan ds. Umiędzynarodowienia i Rozwoju",
            "Prodziekan ds. Nauki",
            "Sekcja Informatyczna Wydziału Matematyki, Fizyki i Informatyki (K005)",
            "Prodziekan ds. Studenckich i Kształcenia",
            "Biuro Dziekana (K002)",
            "Dziekanat (K001)",
            "Zespół obsługi jednostek wydziałowych (K004)",
            "Instytut Matematyki (K100)",
            "Zakład Analizy Matematycznej (K101)",
            "Zakład Funkcji Rzeczywistych (K102)",
            "Zakład Matematyki Stosowanej i Probabilistyki (K103)",
            "Zakład Teorii Mnogości (K105)",
            "Zakład Topologii (K106)",
            "Zakład Algebry (K107)",
            "Zakład Geometrii (K108)",
            "Zakład Dydaktyki Matematyki (K110)",
            "Instytut Informatyki (K300)",
            "Zakład Inżynierii Oprogramowania (K304)",
            "Zakład Informatyki Kwantowej (K305)",
            "Zakład Optymalizacji Kombinatorycznej (K301)",
            "Zakład Języków Formalnych (K302)",
            "Zakład Sztucznej Inteligencji (K303)",
            "Instytut Fizyki Doświadczalnej (K200)",
            "Zakład Fizykochemii Powierzchni i Zjawisk Międzyfazowych (K209)",
            "Zakład Spektroskopii Fazy Skondensowanej (K203)",
            "Zakład Biomateriałów i Fizyki Medycznej (K204)",
            "Zakład Fizyki Stosowanej (K205)",
            "Zakład Fizyki Atomowej i Molekularnej (K210)",
            "Laboratorium Charakteryzacji Materiałów Luminescencyjnych i Nanomateriałów (K207)",
            "Laboratorium Dydaktyki Fizyki (K208)",
            "Instytut Fizyki Teoretycznej i Astrofizyki (K400)",
            "Zakład Spektroskopii Atomowo-Molekularnej i Astrofizyki (K401)",
            "Zakład Metod Matematycznych Fizyki (K402)",
            "Zakład Optyki i Informacji Kwantowej (K403)",
            "Wydział Nauk Społecznych (W000)",
            "Dziekan Wydziału Nauk Społecznych",
            "Prodziekan ds. Kształcenia",
            "Prodziekan ds. Badań Naukowych i Współpracy Międzynarodowej",
            "Prodziekan ds. Studenckich",
            "Biuro Dziekana (W002)",
            "Sekcja Informatyczna Wydziału Nauk Społecznych (W004)",
            "Dziekanat Wydziału Nauk Społecznych (W001)",
            "Instytut Geografii Społeczno-Ekonomicznej i Gospodarki Przestrzennej (W700)",
            "Zakład Badań Krajobrazu i Kształtowania Środowiska (W701)",
            "Zakład Geografii Politycznej (W705)",
            "Zakład Rozwoju Regionalnego (W704)",
            "Pracownia Analiz Terytorialnych (W705)",
            "Zakład Geografii Społeczno-Ekonomicznej (W702)",
            "Zakład Studiów Przestrzennych (W706)",
            "Instytut Mediów, Dziennikarstwa i Komunikacji Społecznej (W300)",
            "Zakład Komunikacji Społecznej i Kulturowej (W304)",
            "Zakład Teorii, Historii i Języka Mediów (W301)",
            "Zakład Antropologii Obrazu (W302)",
            "Zakład Dziennikarstwa i Mediów (W303)",
            "Studio Radiowe-Radio MORS",
            "Instytut Socjologii (W200)",
            "Zakład Teorii Socjologicznej i Metodologii Badań Społecznych (W201)",
            "Zakład Socjologii Życia Codziennego (W204)",
            "Pomorska Pracownia Badań nad Kulturą (W206)",
            "Zakład Socjologii Stosowanej (W205)",
            "Pracownia Realizacji Badań Socjologicznych",
            "Zakład Antropologii Społecznej (W203)",
            "Zakład Socjologii Spraw Publicznych i Gospodarki (W202)",
            "Instytut Filozofii (W100)",
            "Zakład Estetyki i Filozofii Kultury (W101)",
            "Zakład Etyki i Filozofii Społecznej (W102)",
            "Zakład Historii Filozofii Starożytnej, Średniowiecznej i Nowożytnej (W103)",
            "Zakład Logiki, Filozofii Nauki i Epistemologii (W104)",
            "Zakład Metafizyki, Filozofii Religii i Filozofii Współczesnej (W105)",
            "Biblioteka Instytutu",
            "Instytut Pedagogiki (W400)",
            "Zakład Pedagogiki Specjalnej (W401)",
            "Pracownia Interdyscyplinarnych Studiów o Niepełnosprawności i Metodologii Badań (W40A)",
            "Zakład Pedagogiki Społecznej (W402)",
            "Zakład Patologii Społecznej i Resocjalizacji (W404)",
            "Zakład Historii Nauki, Oświaty i Wychowania (W405)",
            "Zakład Dydaktyki i Andragogiki (W406)",
            "Zakład Teorii Wychowania i Pedagogiki Opiekuńczej (W407)",
            "Zakład Pedagogiki Ogólnej (W408)",
            "Zakład Filozofii Wychowania i Studiów Kulturowych (W409)",
            "Zakład Badań nad Dzieciństwem i Szkołą (W410)",
            "Pracownia Edukacji Medialnej (W411)",
            "Instytut Psychologii (W500)",
            "Zakład Psychologii Klinicznej i Zdrowia (W515)",
            "Zakład Neuropsychologii (W516)",
            "Zakład Psychologii Ogólnej (W502)",
            "Zakład Psychologii Ekonomicznej i Psychologii Organizacji (W503)",
            "Zakład Psychologii i Psychopatologii Rozwoju (W504)",
            "Zakład Psychologii Osobowości i Psychologii Sądowej (W505)",
            "Zakład Psychologii Społecznej (W506)",
            "Zakład Psychologii Międzykulturowej i Psychologii Rodzaju (W507)",
            "Zakład Badań nad Rodziną i Jakością Życia (W508)",
            "Zakład Psychologii Sportu (W509)",
            "Zakład Psychometrii i Statystyki (W510)",
            "Laboratorium Diagnostyki Psychologicznej (W511)",
            "Pracownia Psychologii Badań Biznesu (W512)",
            "Psychologiczna Poradnia Genetycznych Chorób Rzadkich (W513)",
            "Pracownia Psychologii Środowiskowej i Relacji Międzygrupowych (W514)",
            "Instytut Politologii (W600)",
            "Zakład Teorii Polityki (W601)",
            "Zakład Polityk Publicznych i Administracji (W602)",
            "Zakład Systemów Politycznych (W603)",
            "Zakład Stosunków Międzynarodowych (W604)",
            "Zakład Myśli Politycznej i Historii Najnowszej (W605)",
            "Zakład Nauk o Bezpieczeństwie (W606)",
            "Zakład Kultury Politycznej (W607)",
            "Sekcja Informatyczna Wydziału Nauk Społecznych (W004)",
            "Wydział Oceanografii i Geografii (O000)",
            "Dziekan Wydziału Oceanografii i Geografii",
            "Prodziekan ds. Nauki i Rozwoju",
            "Prodziekan ds. Kształcenia",
            "Prodziekan ds. Studenckich",
            "Biuro Dziekana (O002)",
            "Dziekanat Wydziału Oceanografii i Geografii (O001)",
            "Katedra Biologii Morza i Biotechnologii (O300)",
            "Pracownia Akwakultury (O301)",
            "Pracownia Fykologii (O304)",
            "Pracownia Biologii Planktonu (O302)",
            "Pracownia Biotechnologii Morskiej (O303)",
            "Katedra Ekologii Morza (O400)",
            "Pracownia Ekofizjologii i Bioenergetyki (O404)",
            "Pracownia Ichtiologii (0402)",
            "Pracownia Bioróżnorodności i Funkcjonowania Bentosu (O403)",
            "Katedra Geomorfologii i Geologii Czwartorzędu (O700)",
            "Pracownia Badań Paleośrodowiskowych (O701)",
            "Pracownia Rekonstrukcji Geomorfologicznych (O702)",
            "Katedra Hydrologii (O800)",
            "Pracownia Hydrologii (O801)",
            "Miejskie Laboratorium Badań Środowiskowych (Coastal Cities Living Lab - CCLL) (O271)",
            "Pracownia Limnologii (O802)",
            "Katedra Oceanografii Fizycznej i Badań Klimatu (OA00)",
            "Pracownia Badań Klimatu (OA01)",
            "Pracownia Oceanografii Fizycznej (OA02)",
            "Katedra Funkcjonowania Ekosystemów Morskich (O500)",
            "Katedra Oceanografii Chemicznej i Geologii Morza (O900)",
            "Pracownia Ochrony Środowiska Morskiego (O903)",
            "Pracownia Biogeochemicznego Obiegu Pierwiastków (O901)",
            "Pracownia Transformacji Substancji Toksycznych (O904)",
            "Pracownia Geologii Morza (O902)",
            "Katedra Geofizyki (O600)",
            "Stacja Morska im. Profesora Krzysztofa Skóry Instytutu Oceanografii w Helu (O011)",
            "Centrum Monitoringu i Ochrony Wód (O010)",
            "Pracownia Systemów Informacji Geograficznej - GIS (O014)",
            "Redakcja Czasopisma \"Oceanological and Hydrobiological Studies\" (O003)",
            "Kolekcja Kultur Glonów Bałtyckich - Culture Collection of Baltic Algae (O012)",
            "Pracownia Aparatury Badawczej (O013)",
            "Wydział Prawa i Administracji (P000)",
            "Dziekan Wydziału Prawa i Administracji",
            "Prodziekan ds. Nauki",
            "Prodziekan ds. Współpracy Międzynarodowej i Rozwoju",
            "Prodziekan ds. Kształcenia",
            "Biuro Dziekana (P002)",
            "Dziekanat Wydziału Prawa i Administracji (P001)",
            "Katedra Historii Prawa (P020)",
            "Katedra Informatyki Prawniczej (P030)",
            "Katedra Postępowania Administracyjnego i Sądowoadministracyjnego (P040)",
            "Katedra Postępowania Cywilnego (P050)",
            "Katedra Prawa Administracyjnego (P070)",
            "Katedra Prawa Cywilnego (P080)",
            "Pracownia Prawa Ubezpieczeniowego (P081)",
            "Zakład Prawa Prywatnego Międzynarodowego (P083)",
            "Zakład Prawa Rzymskiego (P082)",
            "Katedra Praw Człowieka i Prawa Własności Intelektualnej (P060)",
            "Katedra Prawa Europejskiego i Komparatystyki Prawniczej (P190)",
            "Katedra Prawa Finansowego (P090)",
            "Katedra Prawa Gospodarczego Publicznego i Ochrony Środowiska (P100)",
            "Katedra Prawa Handlowego (P010)",
            "Katedra Prawa Karnego Materialnego i Kryminologii (P110)",
            "Zakład Kryminologii (P111)",
            "Katedra Prawa Karnego Procesowego i Kryminalistyki (P120)",
            "Zakład Kryminalistyki i Prawa Dowodowego (P121)",
            "Katedra Prawa Konstytucyjnego i Instytucji Politycznych (P130)",
            "Katedra Prawa Międzynarodowego Publicznego (P140)",
            "Katedra Prawa Morskiego (P150)",
            "Centrum Prawa Nowych Technologii (P400)",
            "Katedra Prawa Pracy (P160)",
            "Katedra Teorii i Filozofii Państwa i Prawa (P170)",
            "Muzeum Kryminalistyki Wydziału Prawa i Administracji (6020)",
            "Biuro Ochrony Danych Osobowych oraz Technik Multimedialnych (P004)",
            "Centrum Prawa Samorządowego i Prawa Finansów Lokalnych (P200)",
            "Międzyuczelniany Wydział Biotechnologii UG i GUMed (Uniwersytetu Gdańskiego i Gdańskiego Uniwersytetu Medycznego) (N000)",
            "Dziekan Międzyuczelnianego Wydziału Biotechnologii",
            "Prodziekan ds. Studenckich i Kształcenia",
            "Prodziekan ds. Nauki",
            "Prodziekan ds. Umiędzynarodowienia i Rozwoju",
            "Biuro Dziekana Międzyuczelnianego Wydziału Biotechnologii UG i GUMed (N002)",
            "Dziekanat Wydziału Biotechnologii (N001)",
            "Jednostki organizacyjne wydziału w Uniwersytecie Gdańskim",
            "Instytut Biotechnologii UG (N100)",
            "Zakład Biochemii Białek (N103)",
            "Zakład Biologii Strukturalnej (N110)",
            "Zakład Ochrony i Biotechnologii Roślin (N107)",
            "Zakład Biologii Molekularnej (N102)",
            "Zakład Fotobiologii i Diagnostyki Molekularnej (N119)",
            "Zakład Biochemii Ewolucyjnej (N101)",
            "Zakład Biochemii Roślin (N113)",
            "Zakład Mikrobiologii Roślin (N120)",
            "Zakład Badania Związków Biologicznie Czynnych (N104)",
            "Zakład Biologii Molekularnej Wirusów (N108)",
            "Zakład Szczepionek Rekombinowanych (N109)",
            "Pracownia Struktury Biopolimerów (N114)",
            "Pracownia Biochemii Fizycznej (N112)",
            "Pracownia Biofizyki (N111)",
            "Pracownia Immunologii Doświadczalnej i Translacyjnej (N116)",
            "Zespół Obsługi Naukowo-Technicznej (N118)",
            "Laboratorium Badawczo-Wdrożeniowe (N117)",
            "Jednostki organizacyjne wydziału w Gdańskim Uniwersytecie Medycznym",
            "Instytut Biotechnologii Medycznej i Onkologii Doświadczalnej GUMed",
            "Zakład Onkologii Translacyjnej",
            "Zakład Biologii Komórki i Immunologii",
            "Zakład Enzymologii i Onkologii Molekularnej",
            "Zakład Bakteriologii Molekularnej",
            "Organizational units common to the University of Gdańsk and the Medical University of Gdańsk",
            "Zespół Laboratoriów Dydaktycznych MWB UG i GUMed (N003)",
            "Zespół Laboratoriów Specjalistycznych MWB UG i GUMed (N004)",
            "Wydział Zarządzania (Z000)",
            "Dziekan Wydziału Zarządzania",
            "Prodziekan ds. Studenckich i Kształcenia",
            "Prodziekan ds. Nauki",
            "Sekcja Informatyczna Wydziału Zarządzania (Z003)",
            "Prodziekan ds. Umiędzynarodowienia i Rozwoju",
            "Dziekanat Wydziału Zarządzania (Z001)",
            "Katedra Organizacji i Zarządzania (Z010)",
            "Zakład Zarządzania Organizacjami Publicznymi (Z014)",
            "Zakład Systemów Zarządzania (Z012)",
            "Zakład Zarządzania Zasobami Ludzkimi (Z013)",
            "Zakład Strategii i Zarządzania Przedsiębiorstwem (Z011)",
            "Katedra Ekonometrii (Z020)",
            "Katedra Strategicznego Rozwoju (Z110)",
            "Zakład Rozwoju i Restrukturyzacji Przedsiębiorstw (Z031)",
            "Zakład Zrównoważonego Rozwoju i Nauk o Jakości (Z112)",
            "Katedra Finansów Przedsiębiorstw (Z040)",
            "Katedra Bankowości i Finansów (Z050)",
            "Katedra Informatyki Ekonomicznej (Z060)",
            "Katedra Inwestycji i Nieruchomości (Z070)",
            "Katedra Marketingu (Z080)",
            "Katedra Rachunkowości (Z090)",
            "Zakład Rachunkowości Finansowej (Z091)",
            "Zakład Rachunkowości Zarządczej (Z092)",
            "Katedra Statystyki (Z100)",
            "Centrum Dydaktyczno-Konferencyjne (Z002)",
            "Akademicki Związek Sportowy (S040)",
            "Klub Uczelniany AZS",
            "Krajowe Centrum Informatyki Kwantowej (S150)",
            "Klub Seniora",
            "Samorząd Studentów UG",
            "Fundacja Rozwoju Uniwersytetu Gdańskiego",
            "Fundacja im. Johanna Gottfrieda Herdera",
            "Gdańska Fundacja Kształcenia Menedżerów",
            "Spółka celowa Univentum Labs sp. z. o. o.",
        };
}
