apiVersion: v1
kind: ConfigMap
metadata:
  name: research-cruise-app-frontend-config
data:
  SENTRY_ENVIRONMENT: staging
  SENTRY_TUNNEL: /api/sentry-tunnel
  SENTRY_TRACES_SAMPLE_RATE: "0.2"
  SENTRY_REPLAYS_SESSION_SAMPLE_RATE: "0.1"
