apiVersion: apps/v1
kind: Deployment
metadata:
  name: research-cruise-app-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: research-cruise-app-frontend
  template:
    metadata:
      labels:
        app: research-cruise-app-frontend
    spec:
      containers:
        - name: research-cruise-app-frontend
          image: research-cruise-app-frontend
          envFrom:
            - configMapRef:
                name: research-cruise-app-frontend-config
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              memory: 10Mi
            requests:
              cpu: 10m
              memory: 10Mi
