pre-commit:
  parallel: true
  commands:
    format-frontend:
      root: frontend/
      run: vp staged
      stage_fixed: true
    format-backend:
      root: backend/
      glob: '**/*.cs'
      run: vp run -F backend staged {staged_files}
      stage_fixed: true
