export enum PathName {
    Default = "/",
    NewForm = "/NewForm",
    SavedApplications = "/SavedForms",
    Form = "/Form",
    ManageUsers = "/ManageUsers",
    Any = "/*",
    Messages = "/Messages",
    Applications = "/Applications",
    MyApplications = "/MyApplications",
    ApplicationDetails = "/ApplicationDetails",
    Cruises = "/Cruises",
    CruiseForm = "/CruiseForm",
    ForcedLogout = "forcedLogout",
    AccountSettings = "/AccountSettings",
    ServerError = "/serverError",
    ConfirmEmail = "/ConfirmEmail",
    Register = "/Register",
    ResetPassword = "ResetPassword"
}