services:
  backend:
    container_name: researchcruiseapp-backend
    image: ghcr.io/vv01t3k/researchcruiseapp/backend
    environment:
      - Database__SeedAutomatically=false
      - Database__MigrateAutomatically=false
      - Database__LogUserPasswordsWhenSeeding=false
      - ConnectionStrings__Database=Server=host.docker.internal,1433;Database=ResearchCruiseApp;User Id=sa;Password=p@ssw0rd;Encrypt=False
      - FrontendUrl=http://localhost:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3000:8080
  frontend:
    container_name: researchcruiseapp-frontend
    image: ghcr.io/vv01t3k/researchcruiseapp/frontend
    ports:
      - 8080:8080
