name: researchcruiseapp

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: researchcruiseapp-db
    environment:
      SA_PASSWORD: "p@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - researchcruiseapp-db:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools*/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -C -Q "SELECT 1" || exit 1
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  researchcruiseapp-db:
