export enum Path {
    Default = "/",
    NewForm = "/NewForm",
    SavedApplications = "/SavedForms",
    Form = "/Form",
    ManageUsers = "/ManageUsers",
    Any = "/*",
    Messages = "/Messages",
    CruiseApplications = "/Applications",
    MyApplications = "/MyCruiseApplications",
    CruiseApplicationDetails = "/CruiseApplicationDetails",
    Cruises = "/Cruises",
    CruiseForm = "/CruiseForm",
    ForcedLogout = "forcedLogout",
    AccountSettings = "/AccountSettings",
    ServerError = "/serverError",
    ConfirmEmail = "/ConfirmEmail",
    Register = "/Register",
    ResetPassword = "/ResetPassword",
    FormAForSupervisor = "/FormAForSupervisor",
    PriorityInformation = "/PriorityInformation",
    HelpInformation = "/HelpInformation",
}