/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PriorityInformationRouteImport } from './routes/priority-information'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CruiseEffectsRouteImport } from './routes/cruise-effects'
import { Route as CruiseApprovalRouteImport } from './routes/cruise-approval'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserManagementIndexRouteImport } from './routes/user-management/index'
import { Route as MyPublicationsIndexRouteImport } from './routes/my-publications/index'
import { Route as CruisesIndexRouteImport } from './routes/cruises/index'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as AccountSettingsIndexRouteImport } from './routes/account-settings/index'
import { Route as CruisesNewRouteImport } from './routes/cruises/new'
import { Route as ApplicationsNewRouteImport } from './routes/applications/new'
import { Route as legacyResetPasswordRouteImport } from './routes/(legacy)/resetPassword'
import { Route as legacyCruiseapprovalRouteImport } from './routes/(legacy)/cruiseapproval'
import { Route as legacyConfirmEmailRouteImport } from './routes/(legacy)/confirmEmail'
import { Route as CruisesCruiseIdIndexRouteImport } from './routes/cruises/$cruiseId/index'
import { Route as ApplicationsApplicationIdFormCRouteImport } from './routes/applications/$applicationId/formC'
import { Route as ApplicationsApplicationIdFormBRouteImport } from './routes/applications/$applicationId/formB'
import { Route as ApplicationsApplicationIdFormARouteImport } from './routes/applications/$applicationId/formA'
import { Route as ApplicationsApplicationIdDetailsRouteImport } from './routes/applications/$applicationId/details'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PriorityInformationRoute = PriorityInformationRouteImport.update({
  id: '/priority-information',
  path: '/priority-information',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CruiseEffectsRoute = CruiseEffectsRouteImport.update({
  id: '/cruise-effects',
  path: '/cruise-effects',
  getParentRoute: () => rootRouteImport,
} as any)
const CruiseApprovalRoute = CruiseApprovalRouteImport.update({
  id: '/cruise-approval',
  path: '/cruise-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementIndexRoute = UserManagementIndexRouteImport.update({
  id: '/user-management/',
  path: '/user-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPublicationsIndexRoute = MyPublicationsIndexRouteImport.update({
  id: '/my-publications/',
  path: '/my-publications/',
  getParentRoute: () => rootRouteImport,
} as any)
const CruisesIndexRoute = CruisesIndexRouteImport.update({
  id: '/cruises/',
  path: '/cruises/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsIndexRoute = AccountSettingsIndexRouteImport.update({
  id: '/account-settings/',
  path: '/account-settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const CruisesNewRoute = CruisesNewRouteImport.update({
  id: '/cruises/new',
  path: '/cruises/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsNewRoute = ApplicationsNewRouteImport.update({
  id: '/applications/new',
  path: '/applications/new',
  getParentRoute: () => rootRouteImport,
} as any)
const legacyResetPasswordRoute = legacyResetPasswordRouteImport.update({
  id: '/(legacy)/resetPassword',
  path: '/resetPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const legacyCruiseapprovalRoute = legacyCruiseapprovalRouteImport.update({
  id: '/(legacy)/cruiseapproval',
  path: '/cruiseapproval',
  getParentRoute: () => rootRouteImport,
} as any)
const legacyConfirmEmailRoute = legacyConfirmEmailRouteImport.update({
  id: '/(legacy)/confirmEmail',
  path: '/confirmEmail',
  getParentRoute: () => rootRouteImport,
} as any)
const CruisesCruiseIdIndexRoute = CruisesCruiseIdIndexRouteImport.update({
  id: '/cruises/$cruiseId/',
  path: '/cruises/$cruiseId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsApplicationIdFormCRoute =
  ApplicationsApplicationIdFormCRouteImport.update({
    id: '/applications/$applicationId/formC',
    path: '/applications/$applicationId/formC',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsApplicationIdFormBRoute =
  ApplicationsApplicationIdFormBRouteImport.update({
    id: '/applications/$applicationId/formB',
    path: '/applications/$applicationId/formB',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsApplicationIdFormARoute =
  ApplicationsApplicationIdFormARouteImport.update({
    id: '/applications/$applicationId/formA',
    path: '/applications/$applicationId/formA',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsApplicationIdDetailsRoute =
  ApplicationsApplicationIdDetailsRouteImport.update({
    id: '/applications/$applicationId/details',
    path: '/applications/$applicationId/details',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/cruise-approval': typeof CruiseApprovalRoute
  '/cruise-effects': typeof CruiseEffectsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/priority-information': typeof PriorityInformationRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/confirmEmail': typeof legacyConfirmEmailRoute
  '/cruiseapproval': typeof legacyCruiseapprovalRoute
  '/resetPassword': typeof legacyResetPasswordRoute
  '/applications/new': typeof ApplicationsNewRoute
  '/cruises/new': typeof CruisesNewRoute
  '/account-settings/': typeof AccountSettingsIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/cruises/': typeof CruisesIndexRoute
  '/my-publications/': typeof MyPublicationsIndexRoute
  '/user-management/': typeof UserManagementIndexRoute
  '/applications/$applicationId/details': typeof ApplicationsApplicationIdDetailsRoute
  '/applications/$applicationId/formA': typeof ApplicationsApplicationIdFormARoute
  '/applications/$applicationId/formB': typeof ApplicationsApplicationIdFormBRoute
  '/applications/$applicationId/formC': typeof ApplicationsApplicationIdFormCRoute
  '/cruises/$cruiseId/': typeof CruisesCruiseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/cruise-approval': typeof CruiseApprovalRoute
  '/cruise-effects': typeof CruiseEffectsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/priority-information': typeof PriorityInformationRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/confirmEmail': typeof legacyConfirmEmailRoute
  '/cruiseapproval': typeof legacyCruiseapprovalRoute
  '/resetPassword': typeof legacyResetPasswordRoute
  '/applications/new': typeof ApplicationsNewRoute
  '/cruises/new': typeof CruisesNewRoute
  '/account-settings': typeof AccountSettingsIndexRoute
  '/applications': typeof ApplicationsIndexRoute
  '/cruises': typeof CruisesIndexRoute
  '/my-publications': typeof MyPublicationsIndexRoute
  '/user-management': typeof UserManagementIndexRoute
  '/applications/$applicationId/details': typeof ApplicationsApplicationIdDetailsRoute
  '/applications/$applicationId/formA': typeof ApplicationsApplicationIdFormARoute
  '/applications/$applicationId/formB': typeof ApplicationsApplicationIdFormBRoute
  '/applications/$applicationId/formC': typeof ApplicationsApplicationIdFormCRoute
  '/cruises/$cruiseId': typeof CruisesCruiseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/cruise-approval': typeof CruiseApprovalRoute
  '/cruise-effects': typeof CruiseEffectsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/priority-information': typeof PriorityInformationRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/(legacy)/confirmEmail': typeof legacyConfirmEmailRoute
  '/(legacy)/cruiseapproval': typeof legacyCruiseapprovalRoute
  '/(legacy)/resetPassword': typeof legacyResetPasswordRoute
  '/applications/new': typeof ApplicationsNewRoute
  '/cruises/new': typeof CruisesNewRoute
  '/account-settings/': typeof AccountSettingsIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/cruises/': typeof CruisesIndexRoute
  '/my-publications/': typeof MyPublicationsIndexRoute
  '/user-management/': typeof UserManagementIndexRoute
  '/applications/$applicationId/details': typeof ApplicationsApplicationIdDetailsRoute
  '/applications/$applicationId/formA': typeof ApplicationsApplicationIdFormARoute
  '/applications/$applicationId/formB': typeof ApplicationsApplicationIdFormBRoute
  '/applications/$applicationId/formC': typeof ApplicationsApplicationIdFormCRoute
  '/cruises/$cruiseId/': typeof CruisesCruiseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-email'
    | '/cruise-approval'
    | '/cruise-effects'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/priority-information'
    | '/register'
    | '/reset-password'
    | '/confirmEmail'
    | '/cruiseapproval'
    | '/resetPassword'
    | '/applications/new'
    | '/cruises/new'
    | '/account-settings/'
    | '/applications/'
    | '/cruises/'
    | '/my-publications/'
    | '/user-management/'
    | '/applications/$applicationId/details'
    | '/applications/$applicationId/formA'
    | '/applications/$applicationId/formB'
    | '/applications/$applicationId/formC'
    | '/cruises/$cruiseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-email'
    | '/cruise-approval'
    | '/cruise-effects'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/priority-information'
    | '/register'
    | '/reset-password'
    | '/confirmEmail'
    | '/cruiseapproval'
    | '/resetPassword'
    | '/applications/new'
    | '/cruises/new'
    | '/account-settings'
    | '/applications'
    | '/cruises'
    | '/my-publications'
    | '/user-management'
    | '/applications/$applicationId/details'
    | '/applications/$applicationId/formA'
    | '/applications/$applicationId/formB'
    | '/applications/$applicationId/formC'
    | '/cruises/$cruiseId'
  id:
    | '__root__'
    | '/'
    | '/confirm-email'
    | '/cruise-approval'
    | '/cruise-effects'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/priority-information'
    | '/register'
    | '/reset-password'
    | '/(legacy)/confirmEmail'
    | '/(legacy)/cruiseapproval'
    | '/(legacy)/resetPassword'
    | '/applications/new'
    | '/cruises/new'
    | '/account-settings/'
    | '/applications/'
    | '/cruises/'
    | '/my-publications/'
    | '/user-management/'
    | '/applications/$applicationId/details'
    | '/applications/$applicationId/formA'
    | '/applications/$applicationId/formB'
    | '/applications/$applicationId/formC'
    | '/cruises/$cruiseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  CruiseApprovalRoute: typeof CruiseApprovalRoute
  CruiseEffectsRoute: typeof CruiseEffectsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  PriorityInformationRoute: typeof PriorityInformationRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  legacyConfirmEmailRoute: typeof legacyConfirmEmailRoute
  legacyCruiseapprovalRoute: typeof legacyCruiseapprovalRoute
  legacyResetPasswordRoute: typeof legacyResetPasswordRoute
  ApplicationsNewRoute: typeof ApplicationsNewRoute
  CruisesNewRoute: typeof CruisesNewRoute
  AccountSettingsIndexRoute: typeof AccountSettingsIndexRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  CruisesIndexRoute: typeof CruisesIndexRoute
  MyPublicationsIndexRoute: typeof MyPublicationsIndexRoute
  UserManagementIndexRoute: typeof UserManagementIndexRoute
  ApplicationsApplicationIdDetailsRoute: typeof ApplicationsApplicationIdDetailsRoute
  ApplicationsApplicationIdFormARoute: typeof ApplicationsApplicationIdFormARoute
  ApplicationsApplicationIdFormBRoute: typeof ApplicationsApplicationIdFormBRoute
  ApplicationsApplicationIdFormCRoute: typeof ApplicationsApplicationIdFormCRoute
  CruisesCruiseIdIndexRoute: typeof CruisesCruiseIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priority-information': {
      id: '/priority-information'
      path: '/priority-information'
      fullPath: '/priority-information'
      preLoaderRoute: typeof PriorityInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruise-effects': {
      id: '/cruise-effects'
      path: '/cruise-effects'
      fullPath: '/cruise-effects'
      preLoaderRoute: typeof CruiseEffectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruise-approval': {
      id: '/cruise-approval'
      path: '/cruise-approval'
      fullPath: '/cruise-approval'
      preLoaderRoute: typeof CruiseApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management/': {
      id: '/user-management/'
      path: '/user-management'
      fullPath: '/user-management/'
      preLoaderRoute: typeof UserManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-publications/': {
      id: '/my-publications/'
      path: '/my-publications'
      fullPath: '/my-publications/'
      preLoaderRoute: typeof MyPublicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruises/': {
      id: '/cruises/'
      path: '/cruises'
      fullPath: '/cruises/'
      preLoaderRoute: typeof CruisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-settings/': {
      id: '/account-settings/'
      path: '/account-settings'
      fullPath: '/account-settings/'
      preLoaderRoute: typeof AccountSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruises/new': {
      id: '/cruises/new'
      path: '/cruises/new'
      fullPath: '/cruises/new'
      preLoaderRoute: typeof CruisesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/new': {
      id: '/applications/new'
      path: '/applications/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof ApplicationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legacy)/resetPassword': {
      id: '/(legacy)/resetPassword'
      path: '/resetPassword'
      fullPath: '/resetPassword'
      preLoaderRoute: typeof legacyResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legacy)/cruiseapproval': {
      id: '/(legacy)/cruiseapproval'
      path: '/cruiseapproval'
      fullPath: '/cruiseapproval'
      preLoaderRoute: typeof legacyCruiseapprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legacy)/confirmEmail': {
      id: '/(legacy)/confirmEmail'
      path: '/confirmEmail'
      fullPath: '/confirmEmail'
      preLoaderRoute: typeof legacyConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruises/$cruiseId/': {
      id: '/cruises/$cruiseId/'
      path: '/cruises/$cruiseId'
      fullPath: '/cruises/$cruiseId/'
      preLoaderRoute: typeof CruisesCruiseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/formC': {
      id: '/applications/$applicationId/formC'
      path: '/applications/$applicationId/formC'
      fullPath: '/applications/$applicationId/formC'
      preLoaderRoute: typeof ApplicationsApplicationIdFormCRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/formB': {
      id: '/applications/$applicationId/formB'
      path: '/applications/$applicationId/formB'
      fullPath: '/applications/$applicationId/formB'
      preLoaderRoute: typeof ApplicationsApplicationIdFormBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/formA': {
      id: '/applications/$applicationId/formA'
      path: '/applications/$applicationId/formA'
      fullPath: '/applications/$applicationId/formA'
      preLoaderRoute: typeof ApplicationsApplicationIdFormARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/details': {
      id: '/applications/$applicationId/details'
      path: '/applications/$applicationId/details'
      fullPath: '/applications/$applicationId/details'
      preLoaderRoute: typeof ApplicationsApplicationIdDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  CruiseApprovalRoute: CruiseApprovalRoute,
  CruiseEffectsRoute: CruiseEffectsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  PriorityInformationRoute: PriorityInformationRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  legacyConfirmEmailRoute: legacyConfirmEmailRoute,
  legacyCruiseapprovalRoute: legacyCruiseapprovalRoute,
  legacyResetPasswordRoute: legacyResetPasswordRoute,
  ApplicationsNewRoute: ApplicationsNewRoute,
  CruisesNewRoute: CruisesNewRoute,
  AccountSettingsIndexRoute: AccountSettingsIndexRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  CruisesIndexRoute: CruisesIndexRoute,
  MyPublicationsIndexRoute: MyPublicationsIndexRoute,
  UserManagementIndexRoute: UserManagementIndexRoute,
  ApplicationsApplicationIdDetailsRoute: ApplicationsApplicationIdDetailsRoute,
  ApplicationsApplicationIdFormARoute: ApplicationsApplicationIdFormARoute,
  ApplicationsApplicationIdFormBRoute: ApplicationsApplicationIdFormBRoute,
  ApplicationsApplicationIdFormCRoute: ApplicationsApplicationIdFormCRoute,
  CruisesCruiseIdIndexRoute: CruisesCruiseIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
