import { CollectedSampleDto } from './CollectedSampleDto';
import { ContractDto } from './ContractDto';
import { CruiseDayDetailsDto } from './CruiseDayDetailsDto';
import { FileDto } from './FileDto';
import { GuestTeamDto } from './GuestTeamDto';
import { LongResearchEquipmentDto } from './LongResearchEquipmentDto';
import { PermissionDto } from './PermissionDto';
import { PortDto } from './PortDto';
import { ResearchAreaDescriptionDto } from './ResearchAreaDescriptionDto';
import { ResearchEquipmentDto } from './ResearchEquipmentDto';
import { ResearchTaskEffectDto } from './ResearchTaskEffectDto';
import { ShortResearchEquipmentDto } from './ShortResearchEquipmentDto';
import { SpubTaskDto } from './SpubTaskDto';
import { UGTeamDto } from './UGTeamDto';

export type FormCDto = {
  shipUsage: string;
  differentUsage: string;
  permissions: PermissionDto[];
  researchAreaDescriptions: ResearchAreaDescriptionDto[];
  ugTeams: UGTeamDto[];
  guestTeams: GuestTeamDto[];
  researchTasksEffects: ResearchTaskEffectDto[];
  contracts: ContractDto[];
  spubTasks: SpubTaskDto[];
  shortResearchEquipments: ShortResearchEquipmentDto[];
  longResearchEquipments: LongResearchEquipmentDto[];
  ports: PortDto[];
  cruiseDaysDetails: CruiseDayDetailsDto[];
  researchEquipments: ResearchEquipmentDto[];
  shipEquipmentsIds: string[];
  collectedSamples: CollectedSampleDto[];
  spubReportData?: string;
  additionalDescription?: string;
  photos: FileDto[];
};
