export const FORM_A_FIELD_TO_SECTION: Record<string, number> = {
  cruiseManagerId: 1,
  deputyManagerId: 1,
  year: 2,
  acceptablePeriod: 2,
  optimalPeriod: 2,
  precisePeriodStart: 2,
  precisePeriodEnd: 2,
  cruiseHours: 2,
  periodNotes: 2,
  shipUsage: 2,
  differentUsage: 2,
  permissions: 3,
  researchAreaDescriptions: 4,
  cruiseGoal: 5,
  cruiseGoalDescription: 5,
  researchTasks: 6,
  contracts: 7,
  ugTeams: 8,
  guestTeams: 8,
  publications: 9,
  spubTasks: 10,
  supervisorEmail: 11,
  note: 11,
};

export const FORM_B_FIELD_TO_SECTION: Record<string, number> = {
  cruiseManagerId: 2,
  deputyManagerId: 2,
  shipUsage: 3,
  differentUsage: 3,
  permissions: 4,
  researchAreaDescriptions: 5,
  cruiseGoal: 6,
  cruiseGoalDescription: 6,
  researchTasks: 7,
  ugTeams: 9,
  guestTeams: 9,
  crewMembers: 9,
  publications: 10,
  cruiseDetailsInfo: 12,
  cruiseDaysDetails: 13,
  researchEquipments: 14,
  shipEquipmentsIds: 15,
  shortResearchEquipments: 14,
  longResearchEquipments: 14,
  ports: 12,
};

export const FORM_C_FIELD_TO_SECTION: Record<string, number> = {
  cruiseManagerId: 2,
  shipUsage: 3,
  differentUsage: 3,
  permissions: 4,
  researchAreaDescriptions: 5,
  cruiseGoal: 6,
  cruiseGoalDescription: 6,
  researchTasksEffects: 7,
  ugTeams: 9,
  guestTeams: 9,
  publications: 10,
  spubTasks: 11,
  cruiseDetailsInfo: 12,
  cruiseDaysDetails: 13,
  researchEquipments: 14,
  shipEquipmentsIds: 15,
  collectedSamples: 16,
  shortResearchEquipments: 14,
  longResearchEquipments: 14,
  ports: 12,
  photos: 18,
  additionalDescription: 18,
  spubReportData: 17,
};
